<?php
/**
 * Copyright 2008 @author_name@
 *
 * This file is part of @plugin_name@.
 * 
 * @plugin_name@ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * @plugin_name@ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with @plugin_name@.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
?>
<a href="<?php echo attribute_escape($this->link_href) ?>"
   title="<?php echo attribute_escape($this->link_title) ?>">
    <?php echo wp_specialchars($this->link_text) ?>
</a>
